---
collections:
  - name: ansible.posix

  - name: ansible.netcommon

  - name: google.cloud

  - name: community.kubernetes

  - name: community.general

  - name: containers.podman

  - name: community.windows
